app/Filament/Forms/Components/PtbrMoney.php, app/Filament/Resources/ProductResource.php
This PR add money fields using ptbr l10n. Also format table fields to money.
Notice:
PtbrMoney is based on Leandro library ([https://github.com/leandrocfe/filament-ptbr-form-fields](https://github.com/leandrocfe/filament-ptbr-form-fields)), but I fixed an issue.
=> [Feature] Add money fields

app/Filament/Resources/OrderResource.php, app/Filament/Resources/OrderResource/Pages/CreateOrder.php, composer.json, composer.lock
Fala Tio!
Segue minha pequena e singela contribuição para o projeto.
Formulário de venda de produtos no admin 
;)
Valewww
=> feat: form order seller admin

app/Providers/Filament/AdminPanelProvider.php, app/Providers/Filament/AppPanelProvider.php, resources/views/filament/partials/logo/brand-logo-dark.blade.php, resources/views/filament/partials/logo/brand-logo.blade.php, resources/views/vendor/filament-panels/components/logo.blade.php
Fala ai, Tio.
Ajustado essa parte das logos. Desculpe, mas esqueci de ter feita uma nova Branch. No fim ficou 3 commits, não sei se vai conseguir ou como funciona, mas qualquer coisa refaço.
=> :bug: fix: adjust the path of the logos

app/Filament/Resources/OrderResource.php
**Local:**  admin/orders/create (step 2)
**O que faz:** Tem como objetivo ocultar o botão "adicionar items" quando a quantidade de itens for igual a quantidade total dos produtos.
_**Obs:** Nunca mexi em filament mas contribuirei com o que eu puder e conseguir :D_
=> Improvement: adding maxItems to hide add item button

README.md, app/Enums/PanelTypeEnum.php, app/Filament/Resources/UserResource.php, app/Filament/Resources/UserResource/Pages/ListUsers.php, app/Models/Customer.php, app/Providers/Filament/AdminPanelProvider.php
Tio, verifiquei e pelo meu pouco conhecimento, a relação entre Customer e Order esta incorreta na parte de Customer. 
A relação delas estão $this->belongsTo(Order::class)  e $this->belongsTo(Customer::class, 'customer_id');
Fiz o ajuste em Customer colocando HasMany e testei e tudo correto.
return $this->hasMany(Order::class, 'customer_id');
OBS: Peço que confirme e caso esteja certo, se puder explicar e tem outras pequenas contribs :)
=> Relations customer has many order

README.md, app/Enums/PanelTypeEnum.php, app/Filament/Resources/UserResource.php
Organizei o topo do README, uns detalhes do resources que faltaram e coloquei no rodapé os contribuidores do projeto.
Uma questão: O correto é eu sempre criar uma branch para cada mudança ou crio uma única branch onde sempre faço as mudanças e vou mandando as PRs por essa?
=> :books: docs: updating readme and adding contributors

README.md
Corrige os imports do Gateway e AssasConnector do arquivo README
=> fix: corrige-imports-do-readme

app/Filament/Resources/OrderResource.php
Remove do formulario de vendas o componente input  bugado
=> fix:remove component input bugado

README.md
Adicionei o mestre Icaro nas contribs e ajustei detelhizinhos nos titles.
=> :books: docs: updated content readme and add Icaro contribs

app/Filament/Resources/OrderResource.php, resources/views/orders/order-resume.blade.php
Adicionando o resumo de items do pedido na parte de pagamento do checkout.
=> feat: Adicionando Resumo do pedido na etapa de pagamento do checkout.

README.md, app/Enums/OrderStatusEnum.php, app/Enums/PanelTypeEnum.php, app/Enums/ProductTransactionTypeEnum.php, app/Filament/Resources/ProductTransactionResource.php
Adicionando icons nos types de OrderStatusEnum, ProductTransactionTypeEnum e em PanelTypeEnum de users. E adicionei Tiago Lemos nas contribs.
=> :bricks: feat: Adding icons to enums and new contributor

README.md, database/migrations/2024_03_07_072512_add_customer_id_column_to_customers_table.php
Tio e galera,
Fiz o teste simulando um DEV clonando o projeto sem o uso do MAKE `meu caso`, então percebi que mesmo fazendo os comandos abaixo necessários, o projeto gera problemas conforme dúvidas no DISCORD onde o Douglas me ajudou.
`comandos`
php artisan migrate:fresh --seed
php artisan shield:install
php artisan storage:link
`Solução proposta`
Defini a coluna de `customer_id` como `nullable()`.
database\migrations\2024_03_07_072512_add_customer_id_column_to_customers_table.php
Se caso não for aceita a PR, se …
=> :boom: fix: Changing the customer_id column to null

app/Filament/Resources/CustomerResource.php, app/Filament/Resources/ProductResource.php, app/Filament/Resources/ProductTransactionResource.php, app/Filament/Resources/UserResource.php
Foi adicionado as `ActionGroup` para `agrupadas as ações e mais clean a view` nas table list de  `user, product, customers e productTransaction `, com `menu de ações`. E adicionei uma ação rápida de modificação do tipo de usuário sem necessidade de entrar em Edit.
=> :rocket: feat: adding user type quick action

app/Enums/BillingTypeEnum.php, app/Enums/OrderTransactionsEnum.php, app/Enums/OrderTransactionsStatusEnum.php, database/migrations/2024_03_12_074612_create_order_transactions_table.php
**Criada a classe OrderTransactionsEnum e alteração na migrations order transactions também foi adicionado a classe de BillingTypeEnum para uso futuramente**
**Este PR apresenta uma mudança significativa?**
Abraço TIO, obrigado por me ajudar com todo seu conhecimento.
=> Criação da classe ENUM OrderTransactionsStatusEnum e BillingTypeEnum.

app/Filament/Pages/Auth/FreezerControlRegister.php, database/migrations/2024_03_12_074612_create_order_transactions_table.php, resources/views/orders/qr-code-generate.blade.php
=> Tio cheio de medo mas tentei, lembre se ainda estou aprendendo. Por favor revise.

database/migrations/2024_03_12_074612_create_order_transactions_table.php
=> fix: add correct namespace to enum import on migration file

README.md
=> Adicionando os links das dependencias README.md

.github/dependabot.yml
Adicionando o dependabot.yml para atualização dos pacotes. Precisa ajustar se é diário ou mensal.
=> Adicionando o dependabot.yml para atualização de dependencia

resources/views/frontend/home.blade.php, routes/web.php
=> Ajustando as rotas e removendo um blade que não estava sendo utilizado

README.md
=> Atualizando a lista de dependências e links

app/Filament/Resources/OrderResource.php
Página de criação de venda: Essa PR só vai habilitar o campo quantidade após a seleção do item, resolvendo o bug.
=> Fix: enable quantity field after selected item

app/Filament/Pages/Auth/FreezerControlRegister.php
Ao criar um usuário sem inserir token sandbox do Asass (env), dava uma exception:
Tratei inicialmente a resposta do erro, checando se a string retornada do erro é um json válido ou não. Se não for, atribui o texto do erro à variável $errorCode apenas.
=> Fix: Error creating user without inserting Asaas token

app/Filament/Resources/OrderResource.php
Esse PR tem a finalidade de exibir/carregar os dados de cartão de crédito de teste somente quando estivermos em ambiente local.
=> imp: Fill in credit card test data only when in a local environment

app/Filament/Resources/OrderResource.php, app/Filament/Resources/ProductTransactionResource.php, app/Filament/Resources/UserResource.php
Adiciona badges com o total respectivo de cada menu: Usuários, Vendas e Movimentações:
=> imp/feat: Also adding badges in nav: orders, transactions and users

app/Mail/NewCustomerMail.php, resources/views/emails/new-customer.blade.php
Coloquei uma perfumaria melhorzinha na view do email de customer.
obs: nos teste passo o caminho correto da logo, mas pelo que percebi o projeto precisa estar hospedado em servidor para a logo aparecer.
=> :lipstick: feat: improving the email customer view

app/Filament/Pages/Auth/FreezerControlRegister.php
Correção de erro 1062 de email duplicado.
Foi corrigido um erro de email duplicado e até o CPF que devem ser únicos. A tela de Erro ajustado abaixo.
Notification correct:
=> :bug: fix: correction when creating a new duplicate customer

app/Filament/Resources/CustomerResource.php, docker-compose.yml
Adicionado mascara de celular e documento.
Validação de maior idade.
Adicionado pasta local para persistir dados db.
você pode utilizar o comando abaixo para criar as pastas
`mkdir -p ./.dockers/mysql/dbdata`
=> feature: validation and masks

resources/views/vendor/filament-panels/components/logo.blade.php
=> feat: centralizar logo no header

docker-compose.yml
=> Desfazendo docker-compose.yml

app/Filament/Resources/CustomerResource.php, app/Filament/Resources/OrderResource.php, app/Filament/Resources/ProductResource.php, app/Filament/Resources/ProductTransactionResource.php, app/Filament/Resources/UserResource.php
=> feat: estilizando resources

app/Filament/Pages/Auth/FreezerControlRegister.php, app/Filament/Resources/CustomerResource/Pages/CreateCustomer.php, app/Filament/Resources/UserResource/Pages/CreateUser.php
Problema de email ou CPF duplicados no banco.
A regra de negocio é email e CPF únicos e por isso, o projeto hoje gera um erro quando o usuário tenta cadastrar um outro usuário/customer com mesmo e-mail/cpf.
Obs: Espero ter melhorado o código das condições, pois acredito ser mais eficiênte. Combina condições em uma única instrução if, o que vai ser mais eficiente em termos de desempenho e também resulta em menos linhas de código.
=> :bug: fix: ajustando erro de duplicação 1062

app/Console/Commands/NormalizeCustomerIdCommand.php, app/Filament/Resources/CustomerResource/Pages/CreateCustomer.php, app/Services/AsaasPhp/Customer/CreateCustomerFromModel.php, package-lock.json, public/build/manifest.json, routes/web.php
Iniciamos a correção do cadastro do cliente via API do ASAAS. Ainda está dando problema e precisamos verificar o que é.
=> wip: corrigindo criação de clientes na API do ASAAS

app/Filament/Resources/CustomerResource/Pages/CreateCustomer.php, routes/console.php
- [ x] Outro, por favor descreva:
- [ x] Não
Tio, não consigo mais acompanhar ao vivo por causa do horário, porém sempre assisto no dia seguinte.
Na ultima live não estava conectando ao Asaas pois teve um PR que alterou o ASSAS para ASAAS e você não alterou no seu arquivo .env
Como tudo está funcionando, aproveitei e alterei a mensagem de notificação que informa que o CPF e/ou Email já estão cadastrado no sistema.
Sucesso
God Bless You!
=> fix: cadastro-de-cliente-gerando-asaas-id

README.md, composer.json
=> Ajustando o comando composer run install-project alternativa ao make

app/Filament/Resources/CustomerResource.php, app/Filament/Resources/ProductResource.php, app/Filament/Resources/UserResource.php
Foram adicionados o botão para deletar um produto*, e para deletar user e customer**.
*
Deletar produto acredito não interferir, pois quando cliente comprou o produto, ele já pagou e levou. Mas podemos averiguar melhor posteriormente.
**
A deleção de Usuário e Customer, foi adicionado condições, pois se cliente tem ordem (pedido), ele não é deletado.
=> feat: Add botões de deleção com notificações no resources

app/Filament/Resources/OrderResource.php
Minha primeira contribuição em um projeto no github hehe, é nois!
=> :sparkles: feat: enforce-stock-quantity-limit

app/Filament/Resources/OrderResource/Pages/CreateOrder.php, app/Helpers/custom-helpers.php, app/Services/PaymentGateway/Connectors/AsaasConnector.php
- The Payment Gateway Client Response was solved
- Created custom helper to instantiate Gateway
O cliente que batia no ASAAS estava retornando o erro como uma string json. Tratamos para retornar como array e, também, tratamos para exibir o erro correto em um Filament Notification.
Além disso, também criamos o helper global em `custom_helpers.php` chamado `get_gateway` para facilitar a chamada da facade.
=> fix: solve problem of client response

app/Filament/Resources/ProductTransactionResource.php, app/Filament/Resources/SupplierResource.php, app/Filament/Resources/SupplierResource/Pages/CreateSupplier.php, app/Filament/Resources/SupplierResource/Pages/EditSupplier.php, app/Filament/Resources/SupplierResource/Pages/ListSuppliers.php, app/Models/ProductTransaction.php, app/Models/Supplier.php, app/Policies/SupplierPolicy.php, database/migrations/2024_08_27_214807_create_suppliers_table.php, database/migrations/2024_08_27_222209_add_supplier_id_to_product_transactions_table.php
=> Feature supplier
